package com.nuova.model;

// Generated Feb 5, 2016 9:57:12 AM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Caja generated by hbm2java
 */
@Entity
@Table(name = "caja"
        , catalog = "nuova")
public class Caja implements java.io.Serializable {

    private Integer cajaId;
    private Integer concepto;
    private Double ingreso;
    private Double egreso;
    private Date fecha;
    private Integer numeroReferencia;
    private Set<CajaOrden> cajaOrdens = new HashSet<CajaOrden>(0);

    public Caja() {
    }

    public Caja(Integer concepto, Double ingreso, Double egreso, Date fecha, Integer numeroReferencia,
            Set<CajaOrden> cajaOrdens) {
        this.concepto = concepto;
        this.ingreso = ingreso;
        this.egreso = egreso;
        this.fecha = fecha;
        this.numeroReferencia = numeroReferencia;
        this.cajaOrdens = cajaOrdens;
    }

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "caja_id", unique = true, nullable = false)
    public Integer getCajaId() {
        return this.cajaId;
    }

    public void setCajaId(Integer cajaId) {
        this.cajaId = cajaId;
    }

    @Column(name = "concepto")
    public Integer getConcepto() {
        return this.concepto;
    }

    public void setConcepto(Integer concepto) {
        this.concepto = concepto;
    }

    @Column(name = "ingreso", precision = 10, scale = 0)
    public Double getIngreso() {
        return this.ingreso;
    }

    public void setIngreso(Double ingreso) {
        this.ingreso = ingreso;
    }

    @Column(name = "egreso", precision = 10, scale = 0)
    public Double getEgreso() {
        return this.egreso;
    }

    public void setEgreso(Double egreso) {
        this.egreso = egreso;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "fecha", length = 19)
    public Date getFecha() {
        return this.fecha;
    }

    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }

    @Column(name = "numero_referencia")
    public Integer getNumeroReferencia() {
        return this.numeroReferencia;
    }

    public void setNumeroReferencia(Integer numeroReferencia) {
        this.numeroReferencia = numeroReferencia;
    }

    @OneToMany(fetch = FetchType.EAGER, mappedBy = "caja")
    public Set<CajaOrden> getCajaOrdens() {
        return this.cajaOrdens;
    }

    public void setCajaOrdens(Set<CajaOrden> cajaOrdens) {
        this.cajaOrdens = cajaOrdens;
    }

}
