package com.nuova.model;

// Generated Feb 5, 2016 9:57:12 AM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * CajaOrden generated by hbm2java
 */
@Entity
@Table(name = "caja_orden"
        , catalog = "nuova")
public class CajaOrden implements java.io.Serializable {

    private Integer cajaOrdenId;
    private Caja caja;
    private Orden orden;

    public CajaOrden() {
    }

    public CajaOrden(Caja caja, Orden orden) {
        this.caja = caja;
        this.orden = orden;
    }

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "caja_orden_id", unique = true, nullable = false)
    public Integer getCajaOrdenId() {
        return this.cajaOrdenId;
    }

    public void setCajaOrdenId(Integer cajaOrdenId) {
        this.cajaOrdenId = cajaOrdenId;
    }

    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "caja_id")
    public Caja getCaja() {
        return this.caja;
    }

    public void setCaja(Caja caja) {
        this.caja = caja;
    }

    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "orden_id")
    public Orden getOrden() {
        return this.orden;
    }

    public void setOrden(Orden orden) {
        this.orden = orden;
    }

}
