package com.nuova.model;

// Generated Feb 5, 2016 9:57:12 AM by Hibernate Tools 4.3.1


import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Calendar generated by hbm2java
 */
@Entity
@Table(name = "calendario"
        , catalog = "nuova")
public class Calendario implements java.io.Serializable {

    private Integer calendarioId;
    private String resource;
    private Date start;
    private Date end;
    private String title;


    public Calendario() {
    }
    
    
    public Calendario(Integer calendarioId, String resource, Date start,
			Date end, String title) {
		this.calendarioId = calendarioId;
		this.resource = resource;
		this.start = start;
		this.end = end;
		this.title = title;
	}


	@Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "calendario_id", unique = true, nullable = false)
    public Integer getCalendarioId() {
        return this.calendarioId;
    }

    public void setCalendarioId(Integer calendarioId) {
        this.calendarioId = calendarioId;
    }

    @Column(name = "resource")
    public String getResource() {
        return this.resource;
    }

    public void setResource(String resource) {
        this.resource = resource;
    }


    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "start", length = 19)
    public Date getStart() {
    	
        return  this.start;
    }

    public void setStart (Date start) {
        this.start = start;
    }
    
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "end", length = 19)
    public Date getEnd() {
        return this.end;
    }

    public void setEnd (Date end) {
        this.end = end;
    }

    @Column(name = "title", length = 256)
    public String getTitle() {
        return this.title;
    }

    public void setTitle(String title) {
        this.title = title;
    }



}
