package com.nuova.model;

// Generated Apr 25, 2016 10:18:42 PM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Empresas generated by hbm2java
 */
@Entity
@Table(name = "empresas"
        , catalog = "nuova")
public class Empresas implements java.io.Serializable {

    private Integer empresaId;
    private String nombre;
    private Integer trabajaId;

    public Empresas() {
    }

    public Empresas(String nombre, Integer trabajaId) {
        this.nombre = nombre;
        this.trabajaId = trabajaId;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "empresa_id", unique = true, nullable = false)
    public Integer getEmpresaId() {
        return this.empresaId;
    }

    public void setEmpresaId(Integer empresaId) {
        this.empresaId = empresaId;
    }

    @Column(name = "nombre", length = 256)
    public String getNombre() {
        return this.nombre;
    }

    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    @Column(name = "trabaja_id")
    public Integer getTrabajaId() {
        return this.trabajaId;
    }

    public void setTrabajaId(Integer trabajaId) {
        this.trabajaId = trabajaId;
    }

}
