package com.nuova.model;

// Generated Aug 28, 2016 2:45:54 PM by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * HistoriaClinica generated by hbm2java
 */
@Entity
@Table(name = "historia_clinica"
        , catalog = "nuova")
public class HistoriaClinica implements java.io.Serializable {

    private Integer id;
    private Date fecha;
    private Integer pacienteId;

    public HistoriaClinica() {
    }

    public HistoriaClinica(Date fecha, Integer pacienteId) {
        this.fecha = fecha;
        this.pacienteId = pacienteId;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "id", unique = true, nullable = false)
    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "fecha", length = 10)
    public Date getFecha() {
        return this.fecha;
    }

    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }

    @Column(name = "paciente_id")
    public Integer getPacienteId() {
        return this.pacienteId;
    }

    public void setPacienteId(Integer pacienteId) {
        this.pacienteId = pacienteId;
    }

}
