package com.nuova.model;

// Generated Mar 30, 2016 12:00:50 PM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Localidades generated by hbm2java
 */
@Entity
@Table(name = "localidades"
        , catalog = "nuova")
public class Localidades implements java.io.Serializable {

    private Integer localidadId;
    private Integer provinciaId;
    private String nombre;

    public Localidades() {
    }

    public Localidades(Integer provinciaId, String nombre) {
        this.provinciaId = provinciaId;
        this.nombre = nombre;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "localidad_id", unique = true, nullable = false)
    public Integer getLocalidadId() {
        return this.localidadId;
    }

    public void setLocalidadId(Integer localidadId) {
        this.localidadId = localidadId;
    }

    @Column(name = "provincia_id")
    public Integer getProvinciaId() {
        return this.provinciaId;
    }

    public void setProvinciaId(Integer provinciaId) {
        this.provinciaId = provinciaId;
    }

    @Column(name = "nombre", length = 512)
    public String getNombre() {
        return this.nombre;
    }

    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

}
