package com.nuova.model;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

	/**
	 * Calendar generated by hbm2java
	 */
	@Entity
	@Table(name = "log_ingresos"
	        , catalog = "nuova")
	public class LogIngresos implements java.io.Serializable {
		
		private Integer id;
		private String usuario;
		private Date fecha;
		
		public LogIngresos(){
			
		}
		
		public LogIngresos(Integer id, String usuario, Date fecha) {
			super();
			this.id=id;
			this.usuario = usuario;
			this.fecha = fecha;
		}
		
		
		@Id
	    @GeneratedValue(strategy = GenerationType.IDENTITY)
	    @Column(name = "id", unique = true, nullable = false)
		public Integer getId() {
			return id;
		}

		public void setId(Integer id) {
			this.id = id;
		}

		@Column(name = "usuario", length = 256)
		public String getUsuario() {
			return usuario;
		}

		public void setUsuario(String usuario) {
			this.usuario = usuario;
		}

	    @Temporal(TemporalType.TIMESTAMP)
	    @Column(name = "fecha", length = 19)
		public Date getFecha() {
			return fecha;
		}

		public void setFecha(Date fecha) {
			this.fecha = fecha;
		}

}
