package com.nuova.model;

// Generated Jan 5, 2016 11:22:38 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Observaciones generated by hbm2java
 */
@Entity
@Table(name = "observaciones"
        , catalog = "nuova")
public class Observaciones implements java.io.Serializable {

    private Integer observacionId;
    private Orden orden;
    private String observacion;
    private String userName;
    private Date fecha;

    public Observaciones() {
    }

    public Observaciones(Orden orden, String observacion, String userName, Date fecha) {
        this.orden = orden;
        this.observacion = observacion;
        this.userName = userName;
        this.fecha = fecha;
    }

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "observacion_id", unique = true, nullable = false)
    public Integer getObservacionId() {
        return this.observacionId;
    }

    public void setObservacionId(Integer observacionId) {
        this.observacionId = observacionId;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "orden_id")
    public Orden getOrden() {
        return this.orden;
    }

    public void setOrden(Orden orden) {
        this.orden = orden;
    }

    @Column(name = "observacion", length = 512)
    public String getObservacion() {
        return this.observacion;
    }

    public void setObservacion(String observacion) {
        this.observacion = observacion;
    }

    @Column(name = "user_name", length = 160)
    public String getUserName() {
        return this.userName;
    }

    public void setUserName(String userName) {
        this.userName = userName;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "fecha", length = 19)
    public Date getFecha() {
        return this.fecha;
    }

    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }

}
