package com.nuova.model;

// Generated May 18, 2016 1:03:16 PM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * OrdenPrestador generated by hbm2java
 */
@Entity
@Table(name = "orden_prestador", catalog = "nuova")
public class OrdenPrestador implements java.io.Serializable {

  private Integer id;
  private Orden orden;
  private Prestadores prestadores;
  private Integer especialidadId;


  public OrdenPrestador() {}

  public OrdenPrestador(Orden orden, Prestadores prestadores, Integer especialidadId) {
    this.orden = orden;
    this.prestadores = prestadores;
    this.especialidadId = especialidadId;
  }

  @Id
  @GeneratedValue(strategy = GenerationType.IDENTITY)
  @Column(name = "id", unique = true, nullable = false)
  public Integer getId() {
    return this.id;
  }

  public void setId(Integer id) {
    this.id = id;
  }

  @ManyToOne(fetch = FetchType.LAZY)
  @JoinColumn(name = "orden_id")
  public Orden getOrden() {
    return this.orden;
  }

  public void setOrden(Orden orden) {
    this.orden = orden;
  }

  @ManyToOne(fetch = FetchType.LAZY)
  @JoinColumn(name = "prestador_id")
  public Prestadores getPrestadores() {
    return this.prestadores;
  }

  public void setPrestadores(Prestadores prestadores) {
    this.prestadores = prestadores;
  }

  @Column(name = "especialidad_id")
  public Integer getEspecialidadId() {
    return this.especialidadId;
  }

  public void setEspecialidadId(Integer especialidadId) {
    this.especialidadId = especialidadId;
  }



}
