package com.nuova.model;

// Generated Feb 3, 2016 10:56:36 AM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * OrdenTipo generated by hbm2java
 */
@Entity
@Table(name = "orden_tipo"
        , catalog = "nuova")
public class OrdenTipo implements java.io.Serializable {

    private Integer ordenTipoId;
    private String nombre;
    private Double monto1;
    private Double monto2;
    private Double monto3;
    private Set<Orden> ordens = new HashSet<Orden>(0);
    private Integer codigo;

    public OrdenTipo() {
    }

    public OrdenTipo(String nombre, Double monto1, Double monto2, Double monto3, Set<Orden> ordens) {
        this.nombre = nombre;
        this.monto1 = monto1;
        this.monto2 = monto2;
        this.monto3 = monto3;
        this.ordens = ordens;
    }

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "orden_tipo_id", unique = true, nullable = false)
    public Integer getOrdenTipoId() {
        return this.ordenTipoId;
    }

    public void setOrdenTipoId(Integer ordenTipoId) {
        this.ordenTipoId = ordenTipoId;
    }

    @Column(name = "nombre", length = 256)
    public String getNombre() {
        return this.nombre;
    }

    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    @Column(name = "monto_1", precision = 10)
    public Double getMonto1() {
        return this.monto1;
    }

    public void setMonto1(Double monto1) {
        this.monto1 = monto1;
    }

    @Column(name = "monto_2", precision = 10)
    public Double getMonto2() {
        return this.monto2;
    }

    public void setMonto2(Double monto2) {
        this.monto2 = monto2;
    }

    @Column(name = "monto_3", precision = 10)
    public Double getMonto3() {
        return this.monto3;
    }

    public void setMonto3(Double monto3) {
        this.monto3 = monto3;
    }

    @OneToMany(fetch = FetchType.EAGER, mappedBy = "ordenTipo")
    public Set<Orden> getOrdens() {
        return this.ordens;
    }

    public void setOrdens(Set<Orden> ordens) {
        this.ordens = ordens;
    }

    @Column(name = "codigo")
    public Integer getCodigo() {
        return codigo;
    }

    public void setCodigo(Integer codigo) {
        this.codigo = codigo;
    }

}
