package com.nuova.model;

// Generated Feb 4, 2016 11:11:44 AM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * OrdenProfesional generated by hbm2java
 */
@Entity
@Table(name = "orden_profesional", catalog = "nuova")
public class OrdenProfesional implements java.io.Serializable {

  private Integer ordenProfesionalId;
  private Orden orden;
  private Profesional profesional;
  private Integer especialidadId;

  public OrdenProfesional() {}

  public OrdenProfesional(Orden orden, Profesional profesional) {
    this.orden = orden;
    this.profesional = profesional;
  }

  @Id
  @GeneratedValue(strategy = GenerationType.IDENTITY)
  @Column(name = "orden_profesional_id", unique = true, nullable = false)
  public Integer getOrdenProfesionalId() {
    return this.ordenProfesionalId;
  }

  public void setOrdenProfesionalId(Integer ordenProfesionalId) {
    this.ordenProfesionalId = ordenProfesionalId;
  }

  @ManyToOne(fetch = FetchType.EAGER)
  @JoinColumn(name = "orden_id")
  public Orden getOrden() {
    return this.orden;
  }

  public void setOrden(Orden orden) {
    this.orden = orden;
  }

  @ManyToOne(fetch = FetchType.EAGER)
  @JoinColumn(name = "profesional_id")
  public Profesional getProfesional() {
    return this.profesional;
  }

  public void setProfesional(Profesional profesional) {
    this.profesional = profesional;
  }

  @Column(name = "especialidad_id")
  public Integer getEspecialidadId() {
    return especialidadId;
  }

  public void setEspecialidadId(Integer especialidadId) {
    this.especialidadId = especialidadId;
  }


}
