package com.nuova.model;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * OrdenDocument generated by hbm2java
 */
@Entity
@Table(name = "orden_especialidad", catalog = "nuova")
public class OrdenEspecialidad implements java.io.Serializable {
  @Id
  @GeneratedValue(strategy = GenerationType.IDENTITY)
  @Column(name = "id", unique = true, nullable = false)
  private Integer id;
  @Column(name = "orden_id")
  private Integer ordenId;
  @Column(name = "especialidad_id")
  private Integer especialidadId;
  @Temporal(TemporalType.DATE)
  @Column(name = "fecha", length = 10)
  private Date fecha;

  public OrdenEspecialidad(Integer id, Integer ordenId, Integer especialidadId, Date fecha) {
    super();
    this.id = id;
    this.ordenId = ordenId;
    this.especialidadId = especialidadId;
    this.fecha = fecha;
  }

  public Integer getId() {
    return id;
  }

  public void setId(Integer id) {
    this.id = id;
  }

  public Integer getOrdenId() {
    return ordenId;
  }

  public void setOrdenId(Integer ordenId) {
    this.ordenId = ordenId;
  }

  public Integer getEspecialidadId() {
    return especialidadId;
  }

  public void setEspecialidadId(Integer especialidadId) {
    this.especialidadId = especialidadId;
  }

  public Date getFecha() {
    return fecha;
  }

  public void setFecha(Date fecha) {
    this.fecha = fecha;
  }


}
