package com.nuova.model;

// Generated Jan 11, 2016 12:33:30 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;

/**
 * OrdenPractica generated by hbm2java
 */
@Entity
@Table(name = "orden_practica", catalog = "nuova")
public class OrdenPractica implements java.io.Serializable {

  /**
   * 
   */
  private static final long serialVersionUID = 8742454053094013763L;
  private Integer orddenPracticaId;
  private Orden orden;
  private Nomenclador nomenclador;
  private Date fecha;
  private String estado;
  private BigDecimal valor;
  private Date autorizarAutomatico;
  private String piezaDental;
  private Integer nomencladorId;
  private Integer ordenId;

  public OrdenPractica() {}

  public OrdenPractica(Orden orden, Nomenclador nomenclador, Date fecha, String estado,
      String piezaDental) {
    this.orden = orden;
    this.nomenclador = nomenclador;
    this.fecha = fecha;
    this.estado = estado;
    this.piezaDental = piezaDental;
  }

  @Id
  @GeneratedValue(strategy = GenerationType.IDENTITY)
  @Column(name = "ordden_practica_id", unique = true, nullable = false)
  public Integer getOrddenPracticaId() {
    return this.orddenPracticaId;
  }

  public void setOrddenPracticaId(Integer orddenPracticaId) {
    this.orddenPracticaId = orddenPracticaId;
  }

  @ManyToOne(fetch = FetchType.EAGER)
  @JoinColumn(name = "orden_id")
  public Orden getOrden() {
    return this.orden;
  }

  public void setOrden(Orden orden) {
    this.orden = orden;
  }

  @ManyToOne(fetch = FetchType.LAZY)
  @JoinColumn(name = "nomenclador_id")
  public Nomenclador getNomenclador() {
    return this.nomenclador;
  }

  public void setNomenclador(Nomenclador nomenclador) {
    this.nomenclador = nomenclador;
  }

  @Temporal(TemporalType.DATE)
  @Column(name = "fecha", length = 10)
  public Date getFecha() {
    return this.fecha;
  }

  public void setFecha(Date fecha) {
    this.fecha = fecha;
  }

  @Column(name = "estado", length = 256)
  public String getEstado() {
    return estado;
  }

  public void setEstado(String estado) {
    this.estado = estado;
  }

  @Column(name = "valor", nullable = false, precision = 10)
  public BigDecimal getValor() {
    return valor;
  }

  public void setValor(BigDecimal valor) {
    this.valor = valor;
  }

  @Temporal(TemporalType.DATE)
  @Column(name = "autorizar_automatico", length = 10)
  public Date getAutorizarAutomatico() {
    return autorizarAutomatico;
  }

  public void setAutorizarAutomatico(Date autorizarAutomatico) {
    this.autorizarAutomatico = autorizarAutomatico;
  }

  @Column(name = "pieza_dental", length = 256)
  public String getPiezaDental() {
    return piezaDental;
  }

  public void setPiezaDental(String piezaDental) {
    this.piezaDental = piezaDental;
  }

  @Transient
  public Integer getNomencladorId() {
    return nomencladorId;
  }

  public void setNomencladorId(Integer nomencladorId) {
    this.nomencladorId = nomencladorId;
  }

  @Transient
  public Integer getOrdenId() {
    return ordenId;
  }

  public void setOrdenId(Integer ordenId) {
    this.ordenId = ordenId;
  }



}
