package com.nuova.model;

// Generated Dec 14, 2015 5:12:02 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PacienteObrasocial generated by hbm2java
 */
@Entity
@Table(name = "paciente_obrasocial"
        , catalog = "nuova")
public class PacienteObrasocial implements java.io.Serializable {

    private Integer pacienteObrasocialId;
    private Paciente paciente;
    private Obrasocial obrasocial;
    private String nroCredencial;
    private Byte provisorio;
    private Date fecha;

    public PacienteObrasocial() {
    }

    public PacienteObrasocial(Paciente paciente, Obrasocial obrasocial, String nroCredencial, Byte provisorio,
            Date fecha) {
        this.paciente = paciente;
        this.obrasocial = obrasocial;
        this.nroCredencial = nroCredencial;
        this.provisorio = provisorio;
        this.fecha = fecha;
    }

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "paciente_obrasocial_id", unique = true, nullable = false)
    public Integer getPacienteObrasocialId() {
        return this.pacienteObrasocialId;
    }

    public void setPacienteObrasocialId(Integer pacienteObrasocialId) {
        this.pacienteObrasocialId = pacienteObrasocialId;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "paciente_id")
    public Paciente getPaciente() {
        return this.paciente;
    }

    public void setPaciente(Paciente paciente) {
        this.paciente = paciente;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "obrasocial_id")
    public Obrasocial getObrasocial() {
        return this.obrasocial;
    }

    public void setObrasocial(Obrasocial obrasocial) {
        this.obrasocial = obrasocial;
    }

    @Column(name = "nro_credencial", length = 256)
    public String getNroCredencial() {
        return this.nroCredencial;
    }

    public void setNroCredencial(String nroCredencial) {
        this.nroCredencial = nroCredencial;
    }

    @Column(name = "provisorio")
    public Byte getProvisorio() {
        return this.provisorio;
    }

    public void setProvisorio(Byte provisorio) {
        this.provisorio = provisorio;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "fecha", length = 10)
    public Date getFecha() {
        return this.fecha;
    }

    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }

}
