package com.nuova.model;

// Generated Dec 17, 2015 7:14:16 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Paciente generated by hbm2java
 */
@Entity
@Table(name = "paciente"
        , catalog = "nuova")
public class Paciente implements java.io.Serializable {

    /**
     * 
     */
    private static final long serialVersionUID = 1623880535481351173L;
    private Integer pacienteId;
    private Paciente paciente;
    private String apellido;
    private String nombre;
    private Date fechaNacimiento;
    private String domicilio;
    private String telefono;
    private String mail;
    private Byte liberado;
    private Integer dni;
    private Set<PacienteObrasocial> pacienteObrasocials = new HashSet<PacienteObrasocial>();
    private Set<Paciente> pacientes = new HashSet<Paciente>();
    private String provincia;
    private Byte titular;

    public Paciente() {
    }

    public Paciente(Paciente paciente, String apellido, String nombre, Date fechaNacimiento, String domicilio,
            String telefono, String mail, Byte liberado, Integer dni, Set<PacienteObrasocial> pacienteObrasocials,
            Set<Paciente> pacientes, String provincia) {
        this.paciente = paciente;
        this.apellido = apellido;
        this.nombre = nombre;
        this.fechaNacimiento = fechaNacimiento;
        this.domicilio = domicilio;
        this.telefono = telefono;
        this.mail = mail;
        this.liberado = liberado;
        this.dni = dni;
        this.pacienteObrasocials = pacienteObrasocials;
        this.pacientes = pacientes;
    }

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "paciente_id", unique = true, nullable = false)
    public Integer getPacienteId() {
        return this.pacienteId;
    }

    public void setPacienteId(Integer pacienteId) {
        this.pacienteId = pacienteId;
    }

    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "adherente_id")
    public Paciente getPaciente() {
        return this.paciente;
    }

    public void setPaciente(Paciente paciente) {
        this.paciente = paciente;
    }

    @Column(name = "apellido", length = 256)
    public String getApellido() {
        return this.apellido;
    }

    public void setApellido(String apellido) {
        this.apellido = apellido;
    }

    @Column(name = "nombre", length = 256)
    public String getNombre() {
        return this.nombre;
    }

    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "fecha_nacimiento", length = 10)
    public Date getFechaNacimiento() {
        return this.fechaNacimiento;
    }

    public void setFechaNacimiento(Date fechaNacimiento) {
        this.fechaNacimiento = fechaNacimiento;
    }

    @Column(name = "domicilio", length = 512)
    public String getDomicilio() {
        return this.domicilio;
    }

    public void setDomicilio(String domicilio) {
        this.domicilio = domicilio;
    }

    @Column(name = "telefono", length = 56)
    public String getTelefono() {
        return this.telefono;
    }

    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }

    @Column(name = "mail", length = 128)
    public String getMail() {
        return this.mail;
    }

    public void setMail(String mail) {
        this.mail = mail;
    }

    @Column(name = "liberado")
    public Byte getLiberado() {
        return this.liberado;
    }

    public void setLiberado(Byte liberado) {
        this.liberado = liberado;
    }

    @Column(name = "dni")
    public Integer getDni() {
        return this.dni;
    }

    public void setDni(Integer dni) {
        this.dni = dni;
    }

    @OneToMany(fetch = FetchType.EAGER, mappedBy = "paciente")
    public Set<PacienteObrasocial> getPacienteObrasocials() {
        return this.pacienteObrasocials;
    }

    public void setPacienteObrasocials(Set<PacienteObrasocial> pacienteObrasocials) {
        this.pacienteObrasocials = pacienteObrasocials;
    }

    @OneToMany(fetch = FetchType.EAGER, mappedBy = "paciente")
    public Set<Paciente> getPacientes() {
        return this.pacientes;
    }

    public void setPacientes(Set<Paciente> pacientes) {
        this.pacientes = pacientes;
    }

    @Column(name = "provincia", length = 156)
    public String getProvincia() {
        return this.provincia;
    }

    public void setProvincia(String provincia) {
        this.provincia = provincia;
    }

    @Column(name = "titular")
    public Byte getTitular() {
        return this.titular;
    }

    public void setTitular(Byte titular) {
        this.titular = titular;
    }
}
