package com.nuova.model;

// Generated Jan 11, 2016 12:33:30 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Practica generated by hbm2java
 */
@Entity
@Table(name = "practica"
        , catalog = "nuova")
public class Practica implements java.io.Serializable {

    private Integer practicaId;
    private String codigo;
    private String nombre;
    private Set<OrdenPractica> ordenPracticas = new HashSet<OrdenPractica>(0);

    public Practica() {
    }

    public Practica(String codigo, String nombre, Set<OrdenPractica> ordenPracticas) {
        this.codigo = codigo;
        this.nombre = nombre;
        this.ordenPracticas = ordenPracticas;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "practica_id", unique = true, nullable = false)
    public Integer getPracticaId() {
        return this.practicaId;
    }

    public void setPracticaId(Integer practicaId) {
        this.practicaId = practicaId;
    }

    @Column(name = "codigo", length = 50)
    public String getCodigo() {
        return this.codigo;
    }

    public void setCodigo(String codigo) {
        this.codigo = codigo;
    }

    @Column(name = "nombre", length = 164)
    public String getNombre() {
        return this.nombre;
    }

    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "practica")
    public Set<OrdenPractica> getOrdenPracticas() {
        return this.ordenPracticas;
    }

    public void setOrdenPracticas(Set<OrdenPractica> ordenPracticas) {
        this.ordenPracticas = ordenPracticas;
    }

}
