package com.nuova.model;

// Generated May 12, 2016 5:53:31 PM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * PrestadoresEspecialidad generated by hbm2java
 */
@Entity
@Table(name = "prestadores_especialidad"
        , catalog = "nuova")
public class PrestadoresEspecialidad implements java.io.Serializable {

    private Integer id;
    private Especialidad especialidad;
    private Prestadores prestadores;

    public PrestadoresEspecialidad() {
    }

    public PrestadoresEspecialidad(Especialidad especialidad, Prestadores prestadores) {
        this.especialidad = especialidad;
        this.prestadores = prestadores;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "id", unique = true, nullable = false)
    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "especialidad_id")
    public Especialidad getEspecialidad() {
        return this.especialidad;
    }

    public void setEspecialidad(Especialidad especialidad) {
        this.especialidad = especialidad;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "prestador_id")
    public Prestadores getPrestadores() {
        return this.prestadores;
    }

    public void setPrestadores(Prestadores prestadores) {
        this.prestadores = prestadores;
    }

}
