package com.nuova.model;

// Generated Dec 7, 2015 4:39:53 PM by Hibernate Tools 3.4.0.CR1

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Profesional generated by hbm2java
 */
@Entity
@Table(name = "profesional"
        , catalog = "nuova")
public class Profesional implements java.io.Serializable {

    private Integer profesionalId;
    private String apellido;
    private String nombre;
    private String telefono;
    private String matricula;
    private String registroNacional;
    private String tituloProfesional;
    private Byte habilitacionSiprosa;
    private Date fechaVencimientoHabilitacion;
    private List<ProfesionalEspecialidad> profesionalEspecialidads = new ArrayList<ProfesionalEspecialidad>();

    public Profesional() {
    }

    public Profesional(String apellido, String nombre, String telefono, String matricula, String registroNacional,
            String tituloProfesional, Byte habilitacionSiprosa, Date fechaVencimientoHabilitacion,
            List<ProfesionalEspecialidad> profesionalEspecialidades) {
        this.apellido = apellido;
        this.nombre = nombre;
        this.telefono = telefono;
        this.matricula = matricula;
        this.registroNacional = registroNacional;
        this.tituloProfesional = tituloProfesional;
        this.habilitacionSiprosa = habilitacionSiprosa;
        this.fechaVencimientoHabilitacion = fechaVencimientoHabilitacion;
        this.profesionalEspecialidads = profesionalEspecialidades;
    }

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "profesional_id", unique = true, nullable = false)
    public Integer getProfesionalId() {
        return this.profesionalId;
    }

    public void setProfesionalId(Integer profesionalId) {
        this.profesionalId = profesionalId;
    }

    @Column(name = "apellido", length = 256)
    public String getApellido() {
        return this.apellido;
    }

    public void setApellido(String apellido) {
        this.apellido = apellido;
    }

    @Column(name = "nombre", length = 256)
    public String getNombre() {
        return this.nombre;
    }

    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    @Column(name = "telefono", length = 56)
    public String getTelefono() {
        return this.telefono;
    }

    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }

    @Column(name = "matricula", length = 256)
    public String getMatricula() {
        return this.matricula;
    }

    public void setMatricula(String matricula) {
        this.matricula = matricula;
    }

    @Column(name = "registro_nacional", length = 256)
    public String getRegistroNacional() {
        return this.registroNacional;
    }

    public void setRegistroNacional(String registroNacional) {
        this.registroNacional = registroNacional;
    }

    @Column(name = "titulo_profesional", length = 256)
    public String getTituloProfesional() {
        return this.tituloProfesional;
    }

    public void setTituloProfesional(String tituloProfesional) {
        this.tituloProfesional = tituloProfesional;
    }

    @Column(name = "habilitacion_siprosa")
    public Byte getHabilitacionSiprosa() {
        return this.habilitacionSiprosa;
    }

    public void setHabilitacionSiprosa(Byte habilitacionSiprosa) {
        this.habilitacionSiprosa = habilitacionSiprosa;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "fecha_vencimiento_habilitacion", length = 10)
    public Date getFechaVencimientoHabilitacion() {
        return this.fechaVencimientoHabilitacion;
    }

    public void setFechaVencimientoHabilitacion(Date fechaVencimientoHabilitacion) {
        this.fechaVencimientoHabilitacion = fechaVencimientoHabilitacion;
    }

    @OneToMany(fetch = FetchType.EAGER, mappedBy = "profesional")
    public List<ProfesionalEspecialidad> getProfesionalEspecialidads() {
        return this.profesionalEspecialidads;
    }

    public void setProfesionalEspecialidads(List<ProfesionalEspecialidad> profesionalEspecialidads) {
        this.profesionalEspecialidads = profesionalEspecialidads;
    }

}
