package com.nuova.model;

// Generated Apr 21, 2016 3:50:57 PM by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Reintegro generated by hbm2java
 */
@Entity
@Table(name = "reintegro"
        , catalog = "nuova")
public class Reintegro implements java.io.Serializable {

    private Integer reintegroId;
    private Integer pacienteId;
    private Date fechaDesde;
    private Date fechaReintegro;
    private String profesional;
    private BigDecimal monto;

    public Reintegro() {
    }

    public Reintegro(Integer pacienteId, Date fechaDesde, Date fechaReintegro, String profesional, BigDecimal monto) {
        this.pacienteId = pacienteId;
        this.fechaDesde = fechaDesde;
        this.fechaReintegro = fechaReintegro;
        this.profesional = profesional;
        this.monto = monto;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "reintegro_id", unique = true, nullable = false)
    public Integer getReintegroId() {
        return this.reintegroId;
    }

    public void setReintegroId(Integer reintegroId) {
        this.reintegroId = reintegroId;
    }

    @Column(name = "paciente_id")
    public Integer getPacienteId() {
        return this.pacienteId;
    }

    public void setPacienteId(Integer pacienteId) {
        this.pacienteId = pacienteId;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "fecha_desde", length = 10)
    public Date getFechaDesde() {
        return this.fechaDesde;
    }

    public void setFechaDesde(Date fechaDesde) {
        this.fechaDesde = fechaDesde;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "fecha_reintegro", length = 10)
    public Date getFechaReintegro() {
        return this.fechaReintegro;
    }

    public void setFechaReintegro(Date fechaReintegro) {
        this.fechaReintegro = fechaReintegro;
    }

    @Column(name = "profesional", length = 256)
    public String getProfesional() {
        return this.profesional;
    }

    public void setProfesional(String profesional) {
        this.profesional = profesional;
    }

    @Column(name = "monto", precision = 10)
    public BigDecimal getMonto() {
        return this.monto;
    }

    public void setMonto(BigDecimal monto) {
        this.monto = monto;
    }

}
