package com.nuova.model;

// Generated Jul 2, 2016 2:33:05 PM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * UserDetails generated by hbm2java
 */
@Entity
@Table(name = "user_details"
        , catalog = "nuova")
public class UserDetails implements java.io.Serializable {

    private Integer id;
    private String username;
    private String password;
    private String name;
    private String address;
    private boolean enabled;
    private Set<UsersRoleMap> usersRoleMaps = new HashSet<UsersRoleMap>(0);

    public UserDetails() {
    }

    public UserDetails(String username, String password, String name, boolean enabled) {
        this.username = username;
        this.password = password;
        this.name = name;
        this.enabled = enabled;
    }

    public UserDetails(String username, String password, String name, String address, boolean enabled,
            Set<UsersRoleMap> usersRoleMaps) {
        this.username = username;
        this.password = password;
        this.name = name;
        this.address = address;
        this.enabled = enabled;
        this.usersRoleMaps = usersRoleMaps;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "id", unique = true, nullable = false)
    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    @Column(name = "username", nullable = false, length = 256)
    public String getUsername() {
        return this.username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    @Column(name = "password", nullable = false, length = 50)
    public String getPassword() {
        return this.password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    @Column(name = "name", nullable = false, length = 300)
    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    @Column(name = "address", length = 1000)
    public String getAddress() {
        return this.address;
    }

    public void setAddress(String address) {
        this.address = address;
    }

    @Column(name = "enabled", nullable = false)
    public boolean isEnabled() {
        return this.enabled;
    }

    public void setEnabled(boolean enabled) {
        this.enabled = enabled;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "userDetails")
    public Set<UsersRoleMap> getUsersRoleMaps() {
        return this.usersRoleMaps;
    }

    public void setUsersRoleMaps(Set<UsersRoleMap> usersRoleMaps) {
        this.usersRoleMaps = usersRoleMaps;
    }

}
