package com.nuova.model;

// Generated Jul 2, 2016 2:33:05 PM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * UsersRoleMap generated by hbm2java
 */
@Entity
@Table(name = "users_role_map"
        , catalog = "nuova")
public class UsersRoleMap implements java.io.Serializable {

    private Integer userRolMapId;
    private UserDetails userDetails;
    private UserRoles userRoles;

    public UsersRoleMap() {
    }

    public UsersRoleMap(UserDetails userDetails, UserRoles userRoles) {
        this.userDetails = userDetails;
        this.userRoles = userRoles;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "user_rol_map_id", unique = true, nullable = false)
    public Integer getUserRolMapId() {
        return this.userRolMapId;
    }

    public void setUserRolMapId(Integer userRolMapId) {
        this.userRolMapId = userRolMapId;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "id", nullable = false)
    public UserDetails getUserDetails() {
        return this.userDetails;
    }

    public void setUserDetails(UserDetails userDetails) {
        this.userDetails = userDetails;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "role_id", nullable = false)
    public UserRoles getUserRoles() {
        return this.userRoles;
    }

    public void setUserRoles(UserRoles userRoles) {
        this.userRoles = userRoles;
    }

}
