package com.nuova.model;

// Generated Jul 2, 2016 2:33:05 PM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * UserRoles generated by hbm2java
 */
@Entity
@Table(name = "user_roles"
        , catalog = "nuova")
public class UserRoles implements java.io.Serializable {

    private int roleId;
    private String role;
    private Set<UsersRoleMap> usersRoleMaps = new HashSet<UsersRoleMap>(0);

    public UserRoles() {
    }

    public UserRoles(int roleId, String role) {
        this.roleId = roleId;
        this.role = role;
    }

    public UserRoles(int roleId, String role, Set<UsersRoleMap> usersRoleMaps) {
        this.roleId = roleId;
        this.role = role;
        this.usersRoleMaps = usersRoleMaps;
    }

    @Id
    @Column(name = "role_id", unique = true, nullable = false)
    public int getRoleId() {
        return this.roleId;
    }

    public void setRoleId(int roleId) {
        this.roleId = roleId;
    }

    @Column(name = "role", nullable = false, length = 50)
    public String getRole() {
        return this.role;
    }

    public void setRole(String role) {
        this.role = role;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "userRoles")
    public Set<UsersRoleMap> getUsersRoleMaps() {
        return this.usersRoleMaps;
    }

    public void setUsersRoleMaps(Set<UsersRoleMap> usersRoleMaps) {
        this.usersRoleMaps = usersRoleMaps;
    }

}
